# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14d9b61bcfb89f9e3229c4af856447f6accadc999cacb1746305912bca676f98f7de476d48e38a619caf9d7de0ca3b14c714093ef26eb9db19ef16bbcccdb40a

test:
  secret_key_base: ba2633842d7b947cf5bf608934b72f94a87424d59860892ed2fec21c013d4130339a736df488b3e84cafb7077c488cfda56ff0eed1b53b9976bc200951079cfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
